services:
  web:
    build:
      context: .
      command: bundle exec rails s -b 0.0.0.0
      volumes:
        - .:/rails
      ports:
        - "3000:3000"
      environment:
        - RAILS_ENV=development
      depends_on:
        - db
      env_file:
        - .env

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    
volumes:
  postgres_data