services:
  web:
    build:
      context: .
      command: bundle exec rails s -b 0.0.0.0
      volumes:
        - .:/rails
      ports:
        - "3000:3000"
      environment:
        - DATABASE_URL=postegresql: